# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "docker" do |docker|
    docker.vm.provision :shell, inline: "echo 'Provisioning Docker Instance'"
    docker.vm.box = "ubuntu-xenial-server-64"
    docker.vm.hostname = "docker"

    docker.vm.network "private_network", ip: "192.168.33.10"

    docker.vm.provider :virtualbox do |vb|
      # Don't boot with headless mode
      # vb.gui = true
      vb.name = "docker"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end
end
