# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "aws" do |devops|

    devops.vm.provider :virtualbox do |vb|
      vb.name = "aws"

      # Display the VirtualBox GUI when booting the machine
      vb.gui = true

      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end

    # devops.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    devops.vm.box = "ubuntu-xenial64"
    devops.vm.hostname = "my.aws.io"
    devops.vm.network "private_network", ip: "192.168.1.100"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder.
    # config.vm.synced_folder "../data", "/vagrant_data"

	# All shell commands to install tools and softwares are listed in provision/node.sh
	# config.vm.provision "shell", path: "provision/node.sh", privileged: true   

  end

end
