# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ansible_control" do |ansible_control|
    ansible_control.vm.provision :shell, inline: "echo 'Provisioning Ansible Control Server'"
    ansible_control.vm.box = "ubuntu-xenial-server-64"
    ansible_control.vm.hostname = "ansiblemaster"

    ansible_control.vm.network "private_network", ip: "192.168.33.10"

    ansible_control.vm.provider :virtualbox do |vb|
      # Don't boot with headless mode
      # vb.gui = true
      vb.name = "ansible_control"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.define "ansible_node1" do |ansible_node1|
    ansible_node1.vm.provision :shell, inline: "echo 'Provisioning Ubuntu Node 1'"
    ansible_node1.vm.box = "ubuntu-xenial-server-64"
    ansible_node1.vm.hostname = "ansiblenode1"
    ansible_node1.vm.network "private_network", ip: "192.168.33.20"

    ansible_node1.vm.provider :virtualbox do |vb|
      # vb.gui = true
      vb.name = "ansible_node1"
      vb.customize ["modifyvm", :id, "--memory", "768"]
    end

    #ansible_web1.vm.provision "shell", inline: <<-SHELL
    #  apt-get install vim -y
    #  apt-get install ansible -y
    #SHELL
  end

  config.vm.define "ansible_node2" do |ansible_node2|
    ansible_node2.vm.provision :shell, inline: "echo 'Provisioning Ubuntu Node 2'"
    ansible_node2.vm.box = "ubuntu-xenial-server-64"
    ansible_node2.vm.hostname = "ansiblenode2"
    ansible_node2.vm.network "private_network", ip: "192.168.33.30"

    ansible_node2.vm.provider :virtualbox do |vb|
      # vb.gui = true
      vb.name = "ansible_node2"
      vb.customize ["modifyvm", :id, "--memory", "768"]
    end

    #ansible_web2.vm.provision "shell", inline: <<-SHELL
    #  apt-get install vim -y
    #  apt-get install ansible -y
    #SHELL
  end

  config.vm.define "centos_node" do |centos_node|
    centos_node.vm.provision :shell, inline: "echo 'Provisioning Centos Node'"
    centos_node.vm.box = "centos65"
    centos_node.vm.hostname = "centosnode"
    centos_node.vm.network "private_network", ip: "192.168.33.40"

    centos_node.vm.provider :virtualbox do |vb|
      # vb.gui = true
      vb.name = "centos_node"
      vb.customize ["modifyvm", :id, "--memory", "768"]
    end
  end
end
